# Site settings
title: Subhrajit - Blog
email: techbiglover@gmail.com
description: >
  Data Engineer - GE, Bangalore
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://subhraj07.github.io"
twitter_username: Subhraj07
github_username:  Subhraj07
linkedin_url: in/subhrajit-mohanty-55709b64

# Build settings
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
