# Site settings
title: Subhrajit - Blog
email: techbiglover@gmail.com
description: >
  Data Engineer - New York City, USA
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://subhraj07.github.io" # the base hostname & protocol for your site
twitter_username: Subhraj07
github_username:  Subhraj07
linkedin_url: in/subhrajit-mohanty-55709b64

# Build settings
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
